# Generated by Django 3.1.2 on 2020-10-24 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_date",
                    models.DateTimeField(verbose_name="Activity Date and Time"),
                ),
                ("activity_type", models.CharField(max_length=64)),
                ("activity_steps", models.IntegerField()),
                ("activity_duration", models.IntegerField()),
                ("activity_distance", models.FloatField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="journal.user"
                    ),
                ),
            ],
        ),
    ]
